poseidon:
    Monitor:
        config: True
        logging_file: /poseidonWork/poseidon/logging.json
        logger_level: INFO
        reinvestigation_frequency: 60
        max_concurrent_reinvestigations: 2
        scan_frequency: 5
        rabbit_server: RABBIT_SERVER
        rabbit_port: 5672
        collector_nic: enp7s0f0
        collector_interval: 15
        collector_filter:
        vent_ip: VENT_IP
        vent_port: 8080

    NorthBoundControllerAbstraction:Update_Switch_State:
        config: True
        controller_uri: https://CONTROLLER_IP:8443/api/v1/
        controller_user: CONTROLLER_USER
        controller_pass: CONTROLLER_PASS
