-   repo: git@github.com:pre-commit/pre-commit-hooks
    sha: 3fa02652357ff0dbb42b5bc78c673b7bc105fcf3
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: autopep8-wrapper
    -   id: check-case-conflict
    -   id: check-json
    -   id: pretty-format-json
        args: ['--autofix']
    -   id: double-quote-string-fixer
    -   id: check-yaml
-   repo: git@github.com:asottile/reorder_python_imports
    sha: v0.3.0
    hooks:
    -   id: reorder-python-imports
