dist: xenial

services:
  - redis
language: python
python:
  - "3.6"
install:
  - pip install codecov
  - wget "https://storage.googleapis.com/shellcheck/shellcheck-stable.linux.x86_64.tar.xz"
  - tar --xz -xvf "shellcheck-stable.linux.x86_64.tar.xz"
  - shellcheck() { "shellcheck-stable/shellcheck" "$@"; }
  - shellcheck --version
env:
  - PYTHONPATH=/home/travis/build/$TRAVIS_REPO_SLUG/poseidon:$PYTHONPATH POSEIDON_CONFIG=/home/travis/build/$TRAVIS_REPO_SLUG/config/poseidon.config POSEIDON_TRAVIS=true
jobs:
  include:
  - stage: test
    script: /bin/bash --version && /bin/bash -n installers/debian/postinst installers/debian/preinst installers/debian/prerm installers/debian/postrm installers/debian/config bin/poseidon helpers/run && shellcheck -x -e SC2119 -e SC2129 -e SC2001 installers/debian/postinst installers/debian/preinst installers/debian/prerm installers/debian/postrm installers/debian/config bin/poseidon helpers/run
  - script: pip3 install -r test-requirements.txt && pip3 install -r api/requirements.txt && py.test -v -vv --cov-report term-missing --cov=. -c .coveragerc
before_install:
  - sudo apt-get update
  - sudo apt-get install docker-ce
after_success:
  - codecov
