dist: xenial

services:
  - redis
language: python
python:
  - "3.7"
install:
  - pip install -U pip
  - pip install codecov
  - wget "https://storage.googleapis.com/shellcheck/shellcheck-stable.linux.x86_64.tar.xz"
  - tar --xz -xvf "shellcheck-stable.linux.x86_64.tar.xz"
  - shellcheck() { "shellcheck-stable/shellcheck" "$@"; }
  - shellcheck --version
env:
  - PYTHONPATH=/home/travis/build/$TRAVIS_REPO_SLUG/poseidon:$PYTHONPATH POSEIDON_CONFIG=/home/travis/build/$TRAVIS_REPO_SLUG/config/poseidon.config POSEIDON_TRAVIS=true
jobs:
  include:
  - stage: test
    script: /bin/bash --version && /bin/bash -n bin/poseidon && shellcheck -x -e SC2016 -e SC2119 -e SC2129 -e SC2001 -e SC2044 bin/poseidon
  - script: pip install -r test-requirements.txt && py.test -v -vv --cov-report term-missing --cov=. -c .coveragerc
before_install:
  - sudo apt-get update
  - sudo apt-get install docker-ce
after_success:
  - codecov
