version: '3.7'
services:
    prometheus:
        restart: always
        image: 'prom/prometheus:v2.16.0'
        user: 'root'
        ports:
            - '9090:9090'
        volumes:
            - '${POSEIDON_PREFIX}/opt/prometheus/:/prometheus'
            - './helpers/faucet/prometheus-docker-compose.yml:/etc/prometheus/prometheus.yml'
            - './helpers/faucet/faucet.rules.yml:/etc/prometheus/faucet.rules.yml'
        networks:
            - poseidon
    grafana:
        restart: always
        image: 'grafana/grafana:6.6.1'
        user: 'root'
        ports:
            - '3000:3000'
        volumes:
            - '${POSEIDON_PREFIX}/opt/grafana:/var/lib/grafana'
            - '${POSEIDON_PREFIX}/opt/grafana/provisioning:/etc/grafana/provisioning'
        networks:
            - poseidon
networks:
    poseidon:
